/* ============================================================
    CONFIG
    ============================================================ */
const CONFIG = {
    cols: 10,
    rows: 20,
    cell: 26,                // smaller than before — this is a windowed embed, not a full page

    lockDelay: 500,
    softDropInterval: 45,
    baseGravity: 800,
    gravityStep: 65,
    minGravity: 100,

    das: 170,
    arr: 45,

    colors: {
        I: '#26e5d6',
        O: '#f4d035',
        T: '#b15eff',
        L: '#ff9142',
        J: '#ff3e9a',
        S: '#ff4557',
        Z: '#4cd97b',
    },

    ghostAlpha: 0.20,
    gridLineColor: '#1e2b38',
    boardBg: '#101822',

    useTexture: true,
    textureSrc: 'Pictures/texturetetris.png',
    textureBlendMode: 'overlay',
    textureOpacity: 0.9,
};

/* ============================================================
    SHAPES — spawn matrix per piece, other 3 rotation states are
    generated by rotating 90° CW, three times (matches how SRS
    itself defines rotation states, so kicks line up correctly).
    ============================================================ */
const SPAWN_SHAPES = {
    I: [
        [0,0,0,0],
        [1,1,1,1],
        [0,0,0,0],
        [0,0,0,0],
    ],
    O: [
        [1,1],
        [1,1],
    ],
    T: [
        [0,1,0],
        [1,1,1],
        [0,0,0],
    ],
    L: [
        [0,0,1],
        [1,1,1],
        [0,0,0],
    ],
    J: [
        [1,0,0],
        [1,1,1],
        [0,0,0],
    ],
    S: [
        [0,1,1],
        [1,1,0],
        [0,0,0],
    ],
    Z: [
        [1,1,0],
        [0,1,1],
        [0,0,0],
    ],
};

const PIECE_TYPES = Object.keys(SPAWN_SHAPES);

function rotateMatrix(m) {
    const n = m.length;
    const r = [];
    for (let i = 0; i < n; i++) {
        r.push([]);
        for (let j = 0; j < n; j++) {
            r[i][j] = m[n - 1 - j][i];
        }
    }
    return r;
}

const SHAPES = {};
for (const type of PIECE_TYPES) {
    const states = [SPAWN_SHAPES[type]];
    for (let i = 1; i < 4; i++) states.push(rotateMatrix(states[i - 1]));
    SHAPES[type] = states;
}

/* ============================================================
    SRS WALL KICK TABLES (clockwise transitions only: 0-1, 1-2,
    2-3, 3-0), in grid coordinates where down = +y.
    ============================================================ */
const KICKS_JLSTZ = {
    '0-1': [[0,0], [-1,0], [-1,-1], [0,2], [-1,2]],
    '1-2': [[0,0], [1,0], [1,1], [0,-2], [1,-2]],
    '2-3': [[0,0], [1,0], [1,-1], [0,2], [1,2]],
    '3-0': [[0,0], [-1,0], [-1,1], [0,-2], [-1,-2]],
};

const KICKS_I = {
    '0-1': [[0,0], [-2,0], [1,0], [-2,1], [1,-2]],
    '1-2': [[0,0], [-1,0], [2,0], [-1,-2], [2,1]],
    '2-3': [[0,0], [2,0], [-1,0], [2,-1], [-1,2]],
    '3-0': [[0,0], [1,0], [-2,0], [1,2], [-2,-1]],
};

const KICKS_O = {
    '0-1': [[0,0]], '1-2': [[0,0]], '2-3': [[0,0]], '3-0': [[0,0]],
};

function getKickTable(type) {
    if (type === 'I') return KICKS_I;
    if (type === 'O') return KICKS_O;
    return KICKS_JLSTZ;
}

function shuffle(arr) {
    for (let i = arr.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
}

/* ============================================================
    STATE
    ============================================================ */
const { cols, rows, cell } = CONFIG;

let board = makeEmptyBoard();
let bagQueue = [];
let nextQueue = [];
let current = null;
let lockStartTime = null;
let dropAccumulator = 0;
let softDropping = false;
let lastTime = 0;

let holdType = null;
let canHold = true;

let score = 0;
let lines = 0;
let level = 1;

// 'start' | 'playing' | 'paused' | 'gameover'
let gameState = 'start';

function makeEmptyBoard() {
    return Array.from({ length: rows }, () => Array(cols).fill(null));
}

function refillBag() {
    bagQueue.push(...shuffle([...PIECE_TYPES]));
}

function nextFromBag() {
    if (bagQueue.length === 0) refillBag();
    return bagQueue.shift();
}

function ensureQueue() {
    while (nextQueue.length < 3) nextQueue.push(nextFromBag());
}

function makePiece(type) {
    const matrix = SHAPES[type][0];
    return {
        type,
        rotState: 0,
        matrix,
        color: CONFIG.colors[type],
        x: Math.floor((cols - matrix.length) / 2),
        y: 0,
    };
}

function spawnPiece() {
    ensureQueue();
    const type = nextQueue.shift();
    ensureQueue();

    current = makePiece(type);
    lockStartTime = null;
    dropAccumulator = 0;

    if (collides(current.matrix, current.x, current.y)) {
        triggerGameOver();
    }
}

function collides(matrix, offX, offY) {
    for (let r = 0; r < matrix.length; r++) {
        for (let c = 0; c < matrix.length; c++) {
            if (!matrix[r][c]) continue;
            const boardX = offX + c;
            const boardY = offY + r;
            if (boardX < 0 || boardX >= cols || boardY >= rows) return true;
            if (boardY >= 0 && board[boardY][boardX]) return true;
        }
    }
    return false;
}

function isGrounded() {
    return collides(current.matrix, current.x, current.y + 1);
}

function tryMove(dx, dy) {
    if (!collides(current.matrix, current.x + dx, current.y + dy)) {
        current.x += dx;
        current.y += dy;
        lockStartTime = null;
        return true;
    }
    return false;
}

function tryMoveRaw(dx, dy) {
    if (!collides(current.matrix, current.x + dx, current.y + dy)) {
        current.x += dx;
        current.y += dy;
        return true;
    }
    return false;
}

function tryRotate() {
    const from = current.rotState;
    const to = (from + 1) % 4;
    const newMatrix = SHAPES[current.type][to];
    const kicks = getKickTable(current.type)[`${from}-${to}`];

    for (const [dx, dy] of kicks) {
        if (!collides(newMatrix, current.x + dx, current.y + dy)) {
            current.matrix = newMatrix;
            current.rotState = to;
            current.x += dx;
            current.y += dy;
            lockStartTime = null;
            return true;
        }
    }
    return false;
}

function ghostY() {
    let gy = current.y;
    while (!collides(current.matrix, current.x, gy + 1)) gy++;
    return gy;
}

function hardDrop() {
    let dist = 0;
    while (tryMoveRaw(0, 1)) dist++;
    score += dist * 2;
    lockPiece();
}

function lockPiece() {
    const m = current.matrix;
    for (let r = 0; r < m.length; r++) {
        for (let c = 0; c < m.length; c++) {
            if (!m[r][c]) continue;
            const by = current.y + r;
            const bx = current.x + c;
            if (by >= 0) board[by][bx] = current.color;
        }
    }
    canHold = true;
    clearLines();
    if (gameState !== 'gameover') spawnPiece();
}

function clearLines() {
    let cleared = 0;
    for (let r = rows - 1; r >= 0; r--) {
        if (board[r].every(cellVal => cellVal !== null)) {
            board.splice(r, 1);
            board.unshift(Array(cols).fill(null));
            cleared++;
            r++;
        }
    }
    if (cleared > 0) {
        const points = [0, 100, 300, 500, 800][cleared] * level;
        score += points;
        lines += cleared;
        level = Math.floor(lines / 10) + 1;
        updateStats();
    }
}

function currentGravity() {
    return Math.max(CONFIG.minGravity, CONFIG.baseGravity - (level - 1) * CONFIG.gravityStep);
}

function triggerGameOver() {
    gameState = 'gameover';
    showOverlay('GAME OVER', `Score: ${score} · Lines: ${lines}`, 'RESTART');
}

/* ============================================================
    HOLD
    ============================================================ */
function holdSwap() {
    if (!canHold || gameState !== 'playing' || !current) return;
    canHold = false;

    const curType = current.type;
    if (holdType === null) {
        holdType = curType;
        spawnPiece();
    } else {
        const swapType = holdType;
        holdType = curType;
        current = makePiece(swapType);
        if (collides(current.matrix, current.x, current.y)) {
            triggerGameOver();
        }
    }
    lockStartTime = null;
    dropAccumulator = 0;
}

/* ============================================================
    RENDERING
    ============================================================ */
const boardCanvas = document.getElementById('board');
boardCanvas.width = cols * cell;
boardCanvas.height = rows * cell;
const ctx = boardCanvas.getContext('2d');
ctx.imageSmoothingEnabled = false; // keeps the texture crisp/pixelated when scaled up

let textureImg = null;
let textureReady = false;
if (CONFIG.useTexture) {
    textureImg = new Image();
    textureImg.onload = () => { textureReady = true; };
    textureImg.src = CONFIG.textureSrc;
}

function drawCell(context, x, y, color, alpha = 1, withTexture = true) {
    const px = x * cell + 1;
    const py = y * cell + 1;
    const size = cell - 2;

    context.globalAlpha = alpha;
    context.fillStyle = color;
    context.fillRect(px, py, size, size);

    if (withTexture && CONFIG.useTexture && textureReady) {
        context.globalCompositeOperation = CONFIG.textureBlendMode;
        context.globalAlpha = alpha * CONFIG.textureOpacity;
        context.drawImage(textureImg, px, py, size, size);
        context.globalCompositeOperation = 'source-over';
    }

    context.globalAlpha = 1;
}

function draw() {
    ctx.fillStyle = CONFIG.boardBg;
    ctx.fillRect(0, 0, boardCanvas.width, boardCanvas.height);

    ctx.strokeStyle = CONFIG.gridLineColor;
    ctx.lineWidth = 1;
    for (let c = 0; c <= cols; c++) {
        ctx.beginPath();
        ctx.moveTo(c * cell, 0);
        ctx.lineTo(c * cell, boardCanvas.height);
        ctx.stroke();
    }
    for (let r = 0; r <= rows; r++) {
        ctx.beginPath();
        ctx.moveTo(0, r * cell);
        ctx.lineTo(boardCanvas.width, r * cell);
        ctx.stroke();
    }

    for (let r = 0; r < rows; r++) {
        for (let c = 0; c < cols; c++) {
            if (board[r][c]) drawCell(ctx, c, r, board[r][c]);
        }
    }

    if (current && (gameState === 'playing' || gameState === 'paused')) {
        const gy = ghostY();
        const m = current.matrix;
        for (let r = 0; r < m.length; r++) {
            for (let c = 0; c < m.length; c++) {
                if (!m[r][c]) continue;
                const bx = current.x + c;
                const by = gy + r;
                if (by >= 0) drawCell(ctx, bx, by, current.color, CONFIG.ghostAlpha, false);
            }
        }
        for (let r = 0; r < m.length; r++) {
            for (let c = 0; c < m.length; c++) {
                if (!m[r][c]) continue;
                const bx = current.x + c;
                const by = current.y + r;
                if (by >= 0) drawCell(ctx, bx, by, current.color);
            }
        }
    }
}

function drawMiniShape(canvasEl, type) {
    const nctx = canvasEl.getContext('2d');
    nctx.fillStyle = CONFIG.boardBg;
    nctx.fillRect(0, 0, canvasEl.width, canvasEl.height);
    if (!type) return;

    const shape = SPAWN_SHAPES[type];
    const size = shape.length;
    const miniCell = 16;
    const offX = (canvasEl.width - size * miniCell) / 2;
    const offY = (canvasEl.height - size * miniCell) / 2;

    nctx.fillStyle = CONFIG.colors[type];
    for (let r = 0; r < size; r++) {
        for (let c = 0; c < size; c++) {
            if (shape[r][c]) {
                nctx.fillRect(
                    offX + c * miniCell + 1,
                    offY + r * miniCell + 1,
                    miniCell - 2,
                    miniCell - 2
                );
            }
        }
    }
}

const nextCanvases = [0, 1, 2].map(i => document.getElementById(`next-${i}`));
nextCanvases.forEach(c => { c.width = 120; c.height = 78; });

const holdCanvas = document.getElementById('hold-canvas');
holdCanvas.width = 120;
holdCanvas.height = 78;

function drawSidePanels() {
    ensureQueue();
    nextCanvases.forEach((c, i) => drawMiniShape(c, nextQueue[i]));
    drawMiniShape(holdCanvas, holdType);
    holdCanvas.classList.toggle('used', !canHold);
}

function updateStats() {
    document.getElementById('stat-score').textContent = score;
    document.getElementById('stat-lines').textContent = lines;
    document.getElementById('stat-level').textContent = level;
}

/* ============================================================
    OVERLAY — start screen / pause / game over, same element
    ============================================================ */
const overlay = document.getElementById('overlay');
const overlayTitle = document.getElementById('overlay-title');
const overlaySub = document.getElementById('overlay-sub');
const overlayBtn = document.getElementById('overlay-btn');

function showOverlay(title, sub, btnText) {
    overlayTitle.textContent = title;
    overlaySub.textContent = sub;
    overlayBtn.textContent = btnText;
    overlay.classList.remove('hide');
}
function hideOverlay() {
    overlay.classList.add('hide');
}

function startGame() {
    gameState = 'playing';
    hideOverlay();
    spawnPiece();
}

function togglePause() {
    if (gameState === 'playing') {
        gameState = 'paused';
        showOverlay('PAUSED', '', 'RESUME');
    } else if (gameState === 'paused') {
        gameState = 'playing';
        hideOverlay();
    }
}

function restartGame() {
    board = makeEmptyBoard();
    bagQueue = [];
    nextQueue = [];
    holdType = null;
    canHold = true;
    score = 0;
    lines = 0;
    level = 1;
    updateStats();
    startGame();
}

overlayBtn.addEventListener('click', () => {
    if (gameState === 'start') startGame();
    else if (gameState === 'gameover') restartGame();
    else if (gameState === 'paused') togglePause();
});

/* ============================================================
    INPUT
    ============================================================ */
let dasTimeout = null;
let arrInterval = null;
let heldDir = null;

function startHorizontal(dir) {
    if (heldDir === dir) return;
    stopHorizontal();
    heldDir = dir;
    tryMove(dir, 0);
    dasTimeout = setTimeout(() => {
        arrInterval = setInterval(() => tryMove(dir, 0), CONFIG.arr);
    }, CONFIG.das);
}

function stopHorizontal() {
    clearTimeout(dasTimeout);
    clearInterval(arrInterval);
    dasTimeout = null;
    arrInterval = null;
    heldDir = null;
}

window.addEventListener('keydown', (e) => {
    if (gameState === 'start') {
        if (e.code === 'Space' || e.code === 'Enter') startGame();
        return;
    }
    if (gameState === 'gameover') {
        if (e.code === 'Space' || e.code === 'Enter') restartGame();
        return;
    }
    if (e.code === 'KeyP') {
        togglePause();
        return;
    }
    if (gameState === 'paused') return;

    switch (e.code) {
        case 'ArrowLeft':
            if (!e.repeat) startHorizontal(-1);
            e.preventDefault();
            break;
        case 'ArrowRight':
            if (!e.repeat) startHorizontal(1);
            e.preventDefault();
            break;
        case 'ArrowDown':
            softDropping = true;
            e.preventDefault();
            break;
        case 'ArrowUp':
            if (!e.repeat) tryRotate();
            e.preventDefault();
            break;
        case 'Space':
            if (!e.repeat) hardDrop();
            e.preventDefault();
            break;
        case 'KeyC':
        case 'ShiftLeft':
        case 'ShiftRight':
            if (!e.repeat) holdSwap();
            e.preventDefault();
            break;
    }
});

window.addEventListener('keyup', (e) => {
    switch (e.code) {
        case 'ArrowLeft':
            if (heldDir === -1) stopHorizontal();
            break;
        case 'ArrowRight':
            if (heldDir === 1) stopHorizontal();
            break;
        case 'ArrowDown':
            softDropping = false;
            break;
    }
});

/* ============================================================
    MAIN LOOP — runs continuously so the board/overlay always
    render, but gameplay logic only advances in 'playing' state.
    ============================================================ */
function update(time) {
    const delta = time - lastTime;
    lastTime = time;

    if (gameState === 'playing' && current) {
        dropAccumulator += delta;
        const interval = softDropping ? CONFIG.softDropInterval : currentGravity();

        if (dropAccumulator > interval) {
            dropAccumulator = 0;
            if (tryMoveRaw(0, 1)) {
                lockStartTime = null;
                if (softDropping) score += 1;
            }
        }

        if (isGrounded()) {
            if (lockStartTime === null) lockStartTime = time;
            else if (time - lockStartTime >= CONFIG.lockDelay) {
                lockPiece();
            }
        } else {
            lockStartTime = null;
        }

        updateStats();
    }

    draw();
    drawSidePanels();
    requestAnimationFrame(update);
}

updateStats();
requestAnimationFrame(update);
